#    COPYRIGHT (C) 2024 Mitsubishi Electric Corporation

#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at

#        http://www.apache.org/licenses/LICENSE-2.0

#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

# IO INTERFACE
string interface_name
# BIT_TOP
uint16 bitid
# BIT MASK
uint16 bitmask
# SEND TYPE
string bit_send_type
# INPUT DATA
uint16 input_data
# OUTPUT DATA
uint16 output_data